### PR TITLE
Extend Snapshot Update Workflow to Include Contributors

### PR DESCRIPTION
**Pull request by arjxn-py**
This PR extends the current GitHub Actions workflow that updates Galata snapshots to include the CONTRIBUTOR author association.

A follow up PR for #97 discussed in [comment here](https://github.com/QuantStack/jupytergis/pull/97/files?diff=unified&w=0#r1721973118)

### CODE REVIEW

**Review by martinRenou — COMMENTED** [review]
Actually, I've got mixed feelings about this change, sorry for suggesting it in the other PR.

A one-time contributor (e.g. who just fixed a typo) would be granted this privilege, and this privilege is a potential security breach.

I'd prefer we don't merge this change.

**Comment by arjxn-py** [comment]
> Actually, I've got mixed feelings about this change, sorry for suggesting it in the other PR.
> 
> A one-time contributor (e.g. who just fixed a typo) would be granted this privilege, and this privilege is a potential security breach.
> 
> I'd prefer we don't merge this change.

This sounds fair to me too, Since bot behavior is already fixed in #97 It should be fine to close this one and If needed maybe comeback to it if we have something better that doesn't compromise on security. Thanks for the clearance @martinRenou

**Comment by martinRenou** [comment]
Thanks for your comprehension and again sorry for suggesting opening a PR for it in the first place !

**Comment by arjxn-py** [comment]
> Thanks for your comprehension and again sorry for suggesting opening a PR for it in the first place !

Totally no worries 😄, It was quite non-trivial in the first place hence did not took any time and effort. I'd also prioritize security of the project any day. Glad that you anticipated it.

**Pull request closed without merging**
