### PR TITLE
Add image and video support

### PR DESCRIPTION
**Pull request by gjmooney**
Working towards #11. Adds image and video layers and sources.  

video_layer

image_layer

### CODE REVIEW

**Review by martinRenou — COMMENTED** [review]
Neat!

Couple of comments (we can resolve this in follow-up PRs):
- it would be great to have a Python API for this too `add_video` / `add_image`
- it would be nice to have a toolbar button for image layer and one for video layer which allows creating both the source and the layer at once
- I'm seeing this in the form, I'm not sure if it has to do with my recent PR https://github.com/QuantStack/jupytergis/pull/74 or if it's related to yours
Screenshot from 2024-07-31 08-51-26

**Comment by martinRenou** [comment]
Concerning the form rendering issue, those big buttons that are messing up the rendering should actually be removed by the logic in https://github.com/QuantStack/jupytergis/blob/main/packages/base/src/formbuilder/objectform/baseform.tsx#L128

For a bit of contexts, those buttons are for editing arrays (removing items, moving items around, adding items). We have this logic to remove those buttons because it does not quite make sense to reorder or add/remove items from the arrays in our case.

**Comment by martinRenou** [comment]
Ah I guess it's because your coordinates is an array of arrays and we're not handling that case when removing the array edit buttons.

**Comment by gjmooney** [comment]
> it would be nice to have a toolbar button for image layer and one for video layer which allows creating both the source and the layer at once

I plan on refactoring our commands a bit (something like [this](https://github.com/gjmooney/jupytergis/blob/pm_tiles/packages/base/src/commands.ts#L531)) and wanted to use that as a chance to make sure the toolbar/context menus have all the options we've implemented so far. 

> Ah I guess it's because your coordinates is an array of arrays and we're not handling that case when removing the array edit buttons.

I was able to apply the `ui:options` to the sub-arrays so now it looks like 

new_coords

**Review by martinRenou — APPROVED** [review]
Thanks!

**Pull request merged**
